version: '3.1'

services:

  tgbot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: python3.8 app.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"
