version: '3'

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    command: python app.py
    restart: always
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:12.11-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/12/main
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
