version: '3'

services:
  ui:
    build:
      dockerfile: docker/Dockerfile.ui
      context: .
    container_name: "ui"
    restart: always
    links:
      - api
    env_file: .env
    ports:
      - 8501:8501
    networks:
      - api_network

  api:
    build:
      dockerfile: docker/Dockerfile.api
      context: .
    container_name: "api"
    restart: always
    links:
      - db
    env_file: .env
    networks:
      - api_network

  cron:
    build:
      dockerfile: docker/Dockerfile.cron
      context: .
    container_name: "cron"
    restart: always
    links:
      - db
    env_file: .env
    networks:
      - api_network

  db:
    image: postgres:12.11-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/12/main
    restart: always
    container_name: "db"
    env_file: .env
    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
