version: '3'

services:
  # bot:
  #   build:
  #     dockerfile: docker/Dockerfile.bot
  #     context: .
  #   container_name: "bot"
  #   restart: always
  #   depends_on:
  #     - db
  #   env_file: .env

  ui:
    build:
      dockerfile: docker/Dockerfile.ui
      context: .
    container_name: "ui"
    restart: always
    links:
      - api
    env_file: .env
    ports:
      - 8501:8501

  api:
    build:
      dockerfile: docker/Dockerfile.api
      context: .
    container_name: "api"
    restart: always
    links:
      - db
    env_file: .env
    ports:
      - 80:80

  cron:
    build:
      dockerfile: docker/Dockerfile.cron
      context: .
    container_name: "cron"
    restart: always
    links:
      - db
    env_file: .env

  db:
    image: postgres:12.11-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/12/main
    restart: always
    env_file: .env
    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
