version: '3'

services:
  ui:
    image: ghcr.io/${IMAGE_REPO}_ui:${RELEASE_VERSION}
    container_name: "ui"
    restart: always
    depends_on:
      - api
    env_file: .env
    ports:
      - 8501:4173
    networks:
      - api_network

  api:
    image: ghcr.io/${IMAGE_REPO}_api:${RELEASE_VERSION}
    container_name: "api"
    restart: always
    depends_on:
      - db
      - keycloak
    env_file: .env
    ports:
      - 8000:8000 
    networks:
      - api_network

  cron:
    image: ghcr.io/${IMAGE_REPO}_cron:${RELEASE_VERSION}
    container_name: "cron"
    restart: always
    depends_on:
      - db
    env_file: .env
    shm_size: '2gb'
    networks:
      - api_network

  db:
    image: postgres:12.11-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: "db"
    env_file: .env
    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - api_network

  keycloak-db:
    image: postgres:15-alpine
    volumes:
      - ./keycloak_postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: "keycloak-db"
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak_password}
    networks:
      - api_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: "keycloak"
    restart: always
    depends_on:
      - keycloak-db
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    env_file: .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak_password}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}                                                                                                                                                                                                                                                            
      KC_HOSTNAME: ${VITE_KEYCLOAK_URL}
      KC_HOSTNAME_STRICT: "false"                                                                                                                                                                                                                                                                                                 
      KC_HOSTNAME_STRICT_HTTPS: "false"                                                                                                                                                                                                                                                                                           
      KC_HTTP_ENABLED: "true"                                                                                                                                                                                                                                                                                                     
      KC_PROXY: edge                                                                                                                                                                                                                                                                                                            
      KC_PROXY_ADDRESS_FORWARDING: "true"
      # KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_HTTPS: false
      # KC_HTTP_ENABLED: true
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    command: start --import-realm
    networks:
      - api_network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
