version: '3'

services:
  # bot:
  #   build:
  #     dockerfile: docker/Dockerfile.bot
  #     context: .
  #   container_name: "bot"
  #   restart: always
  #   depends_on:
  #     - db
  #   env_file: .env

  app:
    build:
      dockerfile: docker/Dockerfile.app
      context: .
    container_name: "app"
    restart: always
    links:
      - db
    env_file: .env
    ports:
      - 8501:8501

  db:
    image: postgres:12.11-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/12/main
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
