version: '3'

services:
  ui:
    image: ghcr.io/${IMAGE_REPO}_ui:${RELEASE_VERSION}
    container_name: "ui"
    restart: always
    links:
      - api
    env_file: .env
    ports:
      - 8501:8501
    networks:
      - api_network

  api:
    image: ghcr.io/${IMAGE_REPO}_api:${RELEASE_VERSION}
    container_name: "api"
    restart: always
    links:
      - db
    env_file: .env
    ports:
      - 8000:8000 
    networks:
      - api_network

  cron:
    image: ghcr.io/${IMAGE_REPO}_cron:${RELEASE_VERSION}
    container_name: "cron"
    restart: always
    links:
      - db
    env_file: .env
    networks:
      - api_network

  db:
    image: postgres:12.11-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: "db"
    env_file: .env
    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - api_network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
