"""Add year column

Revision ID: a6b4d6b9f20e
Revises: f64916e678a7
Create Date: 2025-07-15 22:13:32.666654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b4d6b9f20e'
down_revision = 'f64916e678a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actual_players', sa.Column('year', sa.String(), nullable=True))
    op.add_column('coeffs', sa.Column('year', sa.String(), nullable=True))
    op.add_column('fbref_schedules', sa.Column('year', sa.String(), nullable=True))
    op.add_column('lineups', sa.Column('year', sa.String(), nullable=True))
    op.add_column('players', sa.Column('year', sa.String(), nullable=True))
    op.add_column('players_matches', sa.Column('year', sa.String(), nullable=True))
    op.add_column('players_names', sa.Column('year', sa.String(), nullable=True))
    op.add_column('schedules', sa.Column('year', sa.String(), nullable=True))
    op.add_column('sports_players', sa.Column('year', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('year', sa.String(), nullable=True))
    op.add_column('teams_names', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams_names', 'year')
    op.drop_column('tables', 'year')
    op.drop_column('sports_players', 'year')
    op.drop_column('schedules', 'year')
    op.drop_column('players_names', 'year')
    op.drop_column('players_matches', 'year')
    op.drop_column('players', 'year')
    op.drop_column('lineups', 'year')
    op.drop_column('fbref_schedules', 'year')
    op.drop_column('coeffs', 'year')
    op.drop_column('actual_players', 'year')
    # ### end Alembic commands ###
