"""Add ball_recoveries stat

Revision ID: f442e864ac06
Revises: a6b4d6b9f20e
Create Date: 2025-09-21 14:01:34.702301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f442e864ac06'
down_revision = 'a6b4d6b9f20e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fs_players_stats', sa.Column('ball_recoveries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fs_players_stats', 'ball_recoveries')
    # ### end Alembic commands ###
