"""Test migration

Revision ID: f64916e678a7
Revises: 
Create Date: 2025-07-15 06:16:29.448972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64916e678a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squads')
    op.create_index(op.f('ix_teams_names_betcity_name'), 'teams_names', ['betcity_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_names_betcity_name'), table_name='teams_names')
    op.create_table('squads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('league', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('squad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('squads_pkey'))
    )
    # ### end Alembic commands ###
