FROM node:18-alpine

WORKDIR /fantasy_helper

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

ARG VITE_TELEGRAM_BOT_USERNAME
ENV VITE_TELEGRAM_BOT_USERNAME=$VITE_TELEGRAM_BOT_USERNAME

ARG VITE_KEYCLOAK_URL
ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL

ARG VITE_KEYCLOAK_REALM
ENV VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM

ARG VITE_KEYCLOAK_CLIENT_ID
ENV VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID

COPY ./fantasy_helper/ui/package.json /fantasy_helper

RUN npm install
COPY ./fantasy_helper/ui /fantasy_helper

# COPY ./cert[s] /fantasy_helper/certs || true
# Copy certificates only if they exist (for local development with HTTPS)
# COPY ./cert[s] /fantasy_helper/certs/ || true

RUN npm run build && \
    apk add --no-cache ca-certificates && \
    update-ca-certificates

EXPOSE 4173

HEALTHCHECK --interval=30s --timeout=3s \
  # CMD curl --fail https://localhost:4173/ --insecure || exit 1
  CMD curl --fail http://localhost:4173/ || exit 1

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4173"]
