FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN apt-get update -y && apt-get install -y \
    curl \
    python3-dev \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /bot
COPY pyproject.toml uv.lock /bot/
RUN uv sync --extra bot --frozen

COPY . /bot

CMD ["uv", "run", "python", "fantasy_helper/bot.py"]
