INSERT into players_names (league_name, team_name, sports_name, fbref_name, name, timestamp) 
VALUES 
-- England
('England', 'Астон Вилла', 'Джо Госи', 'Joe Gauci', 'Джо Госи', current_timestamp),
-- ('England', 'Борнмут', 'Дин Хейсен', 'Dean Huijsen', 'Дин Хейсен', current_timestamp),
('England', 'Брентфорд', 'Кристиан Нергор', 'Christian Nørgaard', 'Кристиан Нергор', current_timestamp),
('England', 'Брентфорд', 'Игор Тиаго', 'Thiago', 'Игор Тиаго', current_timestamp),
('England', 'Вулверхэмптон', 'Люк Кандл', 'Luke Cundle', 'Люк Кандл', current_timestamp),
('England', 'Саутгемптон', 'Сэм Амо-Амейо', 'Samuel Amo-Ameyaw', 'Сэм Амо-Амейо', current_timestamp),
-- Russia
('Russia', 'Динамо Махачкала', 'Уссем Мрезигу', 'Houssem Eddine Mrezigue', 'Уссем Мрезигу', current_timestamp),
('Russia', 'Краснодар', 'Жоао Виктор Сантос', 'Victor Sá', 'Жоао Виктор Сантос', current_timestamp),
('Russia', 'Краснодар', 'Жоау Баши', 'Batxi', 'Жоау Баши', current_timestamp),
('Russia', 'Крылья Советов', 'Алоис Ороз', 'Dominik Oroz', 'Алоис Ороз', current_timestamp),
('Russia', 'Крылья Советов', 'Фернандо', 'Fernando Costanza', 'Фернандо', current_timestamp),
-- Spain
('Spain', 'Алавес', 'Адриан Пика', 'Kiké', 'Адриан Пика', current_timestamp),
('Spain', 'Реал Мадрид', 'Фран Гонсалес', 'Fran', 'Фран Гонсалес', current_timestamp),
('Spain', 'Реал Сосьедад', 'Хон Андер Оласагасти', 'Jon Magunazelaia', 'Хон Андер Оласагасти', current_timestamp),
('Spain', 'Севилья', 'Эрьян Нюланд', 'Ørjan Nyland', 'Эрьян Нюланд', current_timestamp),
('Spain', 'Севилья', 'Дарио Бенавидес', 'Darío Fuentes', 'Дарио Бенавидес', current_timestamp),
('Spain', 'Севилья', 'Альберто Флорес', 'Alberto López', 'Альберто Флорес', current_timestamp),
('Spain', 'Севилья', 'Álvaro García', 'Álvaro Pascual', 'Álvaro García', current_timestamp),
('Spain', 'Хетафе', 'Джене Даконам', 'Djené', 'Джене Даконам', current_timestamp),
('Spain', 'Хетафе', 'Хуан Иглесиас', 'Iglesias', 'Хуан Иглесиас', current_timestamp),
('Spain', 'Хетафе', 'Йеллу Сантьяго', 'Jesús Santiago', 'Йеллу Сантьяго', current_timestamp),
('Spain', 'Хетафе', 'Гильем Трилья', 'Guillem Cortiñas', 'Гильем Трилья', current_timestamp),
('Spain', 'Хетафе', 'Джон Патрик', 'John Joe', 'Джон Патрик', current_timestamp),
-- France
('France', 'Анжер', 'Карлен Аркю', 'Carlens Arcus', 'Карлен Аркю', current_timestamp),
('France', 'Анжер', 'Эммануэль Биэнла', 'Emmanuel Biumla', 'Эммануэль Биэнла', current_timestamp),
('France', 'Монпелье', 'Кики Куяте', 'Boubakar Kouyaté', 'Кики Куяте', current_timestamp),
('France', 'Монпелье', 'Люка Минкарелли', 'Lucas Mincarelli', 'Люка Минкарелли', current_timestamp),
('France', 'Нант', 'Фабьен Сантонз', 'Fabien Centonze', 'Фабьен Сантонз', current_timestamp),
('France', 'Ренн', 'Андрес Гомес', 'Carlos Gómez', 'Андрес Гомес', current_timestamp),
('France', 'Ренн', 'Микаил Файе', 'Mikayil Ngor Faye', 'Микаил Файе', current_timestamp),
('France', 'Сент-Этьен', 'Эман Эки', 'Ayman Aiki', 'Эман Эки', current_timestamp),
('France', 'Сент-Этьен', 'Иванн Масон', 'Yvann Macon', 'Иванн Масон', current_timestamp),
-- Portugal
('Portugal', 'Боавишта', 'Жулиу Дабу', 'Augusto Dabo', 'Жулиу Дабу', current_timestamp),
('Portugal', 'Витория Гимараэш', 'Хесус Рамирес', 'Jesús Ramírez', 'Хесус Рамирес', current_timestamp),
('Portugal', 'Витория Гимараэш', 'Шарлес да Силва', 'Charles', 'Шарлес да Силва', current_timestamp),
('Portugal', 'Жил Висенте', 'Гонсалу Пинту', 'João Pinto', 'Гонсалу Пинту', current_timestamp),
('Portugal', 'Каза Пия', 'Фахем Бенаисса-Яхья', 'Fahem Benaissa Yahia', 'Фахем Бенаисса-Яхья', current_timestamp),
('Portugal', 'Каза Пия', 'Энрике Перейра', 'Pereira', 'Энрике Перейра', current_timestamp),
('Portugal', 'Каза Пия', 'Гаиска Ларрасабаль', 'Larra', 'Гаиска Ларрасабаль', current_timestamp),
('Portugal', 'Морейренсе', 'Габриэлзиньо', 'Gabriel Airton de Souza', 'Габриэлзиньо', current_timestamp),
('Portugal', 'Насьонал', 'Густаво Гарсия', 'García', 'Густаво Гарсия', current_timestamp),
('Portugal', 'Насьонал', 'Жота Гарсеш', 'João Tiago Serrão Garcês', 'Жота Гарсеш', current_timestamp),
('Portugal', 'Насьонал', 'Жозе Мануэл', 'José Gomes', 'Жозе Мануэл', current_timestamp),
('Portugal', 'Порту', 'Дэнни Намасо', 'Danny Loader', 'Дэнни Намасо', current_timestamp),
('Portugal', 'Порту', 'Франсишку Моура', 'Moura', 'Франсишку Моура', current_timestamp),
('Portugal', 'Риу Аве', 'Джонатан Луис', 'Jhonatan', 'Джонатан Луис', current_timestamp),
('Portugal', 'Риу Аве', 'Фабиу Роналду', 'Fábio Conceição', 'Фабиу Роналду', current_timestamp),
('Portugal', 'Риу Аве', 'Ахмед Хассан', 'Koka', 'Ахмед Хассан', current_timestamp),
('Portugal', 'Риу Аве', 'Жоау Муниш', 'João Nascimento', 'Жоау Муниш', current_timestamp),
('Portugal', 'Санта-Клара', 'Абраан Сарайва', 'Habraão', 'Абраан Сарайва', current_timestamp),
('Portugal', 'Санта-Клара', 'Алиссон Сафира', 'Safira', 'Алиссон Сафира', current_timestamp),
('Portugal', 'Санта-Клара', 'Бруну Алмейда', 'Bruno Messi', 'Бруну Алмейда', current_timestamp),
('Portugal', 'Санта-Клара', 'Габриэл Силва', 'Gabriel Vieira', 'Габриэл Силва', current_timestamp),
('Portugal', 'Санта-Клара', 'Габриэл Соуза', 'Gabriel Batista', 'Габриэл Соуза', current_timestamp),
('Portugal', 'Санта-Клара', 'Клисман', 'Gustavo Klismahn', 'Клисман', current_timestamp),
('Portugal', 'Санта-Клара', 'Матеус Фагундес', 'MT', 'Матеус Фагундес', current_timestamp),
('Portugal', 'Санта-Клара', 'Сержио Лобо', 'Serginho', 'Сержио Лобо', current_timestamp),
('Portugal', 'Санта-Клара', 'Сидней Лима', 'Sidney', 'Сидней Лима', current_timestamp),
('Portugal', 'Эштрела', 'Гильерме Монтойя', 'Guilherme Serrão', 'Гильерме Монтойя', current_timestamp),
('Portugal', 'Эштрела', 'Жоау Кикаш', 'Kikas', 'Жоау Кикаш', current_timestamp),
('Portugal', 'Эштрела', 'Мануэл Келиану', 'Kikas', 'Мануэл Келиану', current_timestamp),
('Portugal', 'Эштрела', 'Эмануэль Кандимба', 'Manú', 'Эмануэль Кандимба', current_timestamp),
('Portugal', 'Эштрела', 'Петтерсон Новаэс', 'Petterson', 'Петтерсон Новаэс', current_timestamp),
('Portugal', 'Эштрела', 'Ферру', 'Francisco Reis Ferreira', 'Ферру', current_timestamp),
('Portugal', 'АВС', 'Луиш Силва', 'Luís Manuel Costa Silva', 'Луиш Силва', current_timestamp),
('Portugal', 'АВС', 'Кики', 'Christian Neiva Afonso', 'Кики', current_timestamp),
-- Netherlands
('Netherlands', 'НАК', 'Мэттью Гарбетт', 'Matt Garbett', 'Мэттью Гарбетт', current_timestamp),
-- Turkey
('Turkey', 'Бодрум', 'Кристоф Эрей', 'Christophe Hérelle', 'Кристоф Эрей', current_timestamp),
('Turkey', 'Истанбул', 'Мигел Крешпу', 'Crespo', 'Мигел Крешпу', current_timestamp),
('Turkey', 'Касымпаша', 'Шант Казанджи', 'Sant Kazanci', 'Шант Казанджи', current_timestamp),
('Turkey', 'Касымпаша', 'Эрдем Четинкая', 'Erdem Çetinkaya', 'Эрдем Четинкая', current_timestamp),
('Turkey', 'Коньяспор', 'Йосип Чалушич', 'Josip Čalušić', 'Йосип Чалушич', current_timestamp),
('Turkey', 'Фенербахче', 'Осман Четин', 'Osman Ertuğrul Çetin', 'Осман Четин', current_timestamp),
-- Championship
('Championship', 'КПР', 'Эверттон', 'Hevertton Santos', 'Эверттон', current_timestamp),
('Championship', 'Кардифф', 'Джек Эник', 'Jak Alnwick', 'Джек Эник', current_timestamp),
('Championship', 'Кардифф', 'Манолис Сиопис', 'Emmanouil Siopis', 'Манолис Сиопис', current_timestamp),
('Championship', 'Лидс', 'Деньян Ньонто', 'Wilfried Gnonto', 'Деньян Ньонто', current_timestamp),
('Championship', 'Норвич', 'Бен Крайзин', 'Benjamin Chrisene', 'Бен Крайзин', current_timestamp),
('Championship', 'Уотфорд', 'Кевен Кебен', 'Kévin Keben Biakolo', 'Кевен Кебен', current_timestamp),
-- Italy
('Italy', 'Верона', 'Иллан Оку', 'Yllan Okou', 'Иллан Оку', current_timestamp),
('Italy', 'Комо', 'Нико Пас', 'Nicolás Paz', 'Нико Пас', current_timestamp),
('Italy', 'Комо', 'Бенжамен Коне', 'Ben Lhassine Kone', 'Бенжамен Коне', current_timestamp),
('Italy', 'Милан', 'Тейани Рейндерс', 'Tijjani Reijnders', 'Тейани Рейндерс', current_timestamp),
('Italy', 'Парма', 'Анас Хадж Мохамед', 'Mohamed Haj', 'Анас Хадж Мохамед', current_timestamp),
('Italy', 'Парма', 'Антуан Эно', 'Antoine Hainaut', 'Антуан Эно', current_timestamp),
-- ('Italy', 'Рома', 'Эван Ндика', "Obite N'Dicka", 'Эван Ндика', current_timestamp),
('Italy', 'Торино', 'Алье Нджи', 'Eybi Nije', 'Алье Нджи', current_timestamp),
('Italy', 'Удинезе', 'Исаак Туре', 'Souleymane Touré', 'Исаак Туре', current_timestamp),
('Italy', 'Эмполи', 'Эмануэль Джаси', 'Emmanuel Gyasi', 'Эмануэль Джаси', current_timestamp),
-- Germany
('Germany', 'Боруссия Д', 'Серу Гирасси', 'Serhou Guirassy', 'Серу Гирасси', current_timestamp),
('Germany', 'Бохум', 'Тим Эрманн', 'Tim Oermann', 'Тим Эрманн', current_timestamp),
('Germany', 'Вольфсбург', 'Седрик Цезигер', 'Cedric Zesiger', 'Седрик Цезигер', current_timestamp),
('Germany', 'Майнц', 'Ли Чжэ Сон', 'Lee Jae-sung', 'Ли Чжэ Сон', current_timestamp),
('Germany', 'Майнц', 'Николас Ферачниг', 'Nikolas Veratschnig', 'Николас Ферачниг', current_timestamp),
('Germany', 'Майнц', 'Филипп Мвене', 'Phillipp Mwene', 'Филипп Мвене', current_timestamp),
('Germany', 'Майнц', 'Хон Хен Сок', 'Hong Hyunseok', 'Хон Хен Сок', current_timestamp),
('Germany', 'Унион Берлин', 'Данило Дуки', 'Danilho Doekhi', 'Данило Дуки', current_timestamp),
('Germany', 'Унион Берлин', 'Диогу Лейте', 'Diogo Leite', 'Диогу Лейте', current_timestamp),
('Germany', 'Унион Берлин', 'Фредерик Реннов', 'Frederik Rønnow', 'Фредерик Реннов', current_timestamp),
('Germany', 'Унион Берлин', 'Люка Тузар', 'Lucas Tousart', 'Люка Тузар', current_timestamp),
('Germany', 'Унион Берлин', 'Чжон Ву Ен', 'Jeong Woo-yeong', 'Чжон Ву Ен', current_timestamp),
('Germany', 'Фрайбург', 'Янник Хут', 'Jannik Huth', 'Янник Хут', current_timestamp),
('Germany', 'Хайденхайм', 'Лука Янеш', 'Luka Janes', 'Лука Янеш', current_timestamp),
('Germany', 'Хайденхайм', 'Витус Айхер', 'Vitus Eicher', 'Витус Айхер', current_timestamp)
;
